### PR TITLE
manicured zen garden

### PR DESCRIPTION
**Pull request by joseph-code-EDA**
My zen garden is ready for your expertise!

### CODE REVIEW

**Comment by SamSimmons** [comment]
I think lines 4 - 11 should be indented, so inside the head tag.

And lines 18 & 19 should be indented because they're inside the header tag.

The only other things are indenting the anchor elements inside li's I personally like them like you've done them, but the style article in our concepts had them indented, and it had p elements indented too.  

https://github.com/dev-academy-programme/curriculum/tree/master/resources/html-formatting-ARTICLE

Nearly perfect though!

**Comment by joseph-code-EDA** [comment]
Thanks @SamSimmons - you're comments and weblink have made me more aware of good semantic structuring & helped me grow. 
I look forward to your comments on the most recent updates.

**Comment by SamSimmons** [comment]
Good stuff joseph, I feel a bit ridiculous being so fussy haha. The one thing left I would say is that the links inside your list items lines 109-116, 125-127 and 135-139 could be nested as well, but other than that I'm happy to merge the pull request!

**Comment by joseph-code-EDA** [comment]
Thanks Sam, I've learned so much more about the importance of indentation - and yes, the code is far easier to read now than before!!!!
Go for the merge!

**Pull request merged**
